version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      TRIPOSR_REPO_DIR: /app/project/external/TripoSR
      TRIPOSR_MODEL_SAVE_FORMAT: glb
    volumes:
      - ./server:/app/server
      - ./project:/app/project
